{% set name = "httomolib" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ..

build:
  preserve_egg_dir: False
  script: {{ PYTHON }} -m pip install -e .
  number: 0

requirements:
  host:
    - python
    - pip
  run:
    - python
    - cupy
    - numpy
    - scipy
    - pillow
    - scikit-image
    - pytest

about:
  home: https://github.com/DiamondLightSource/httomolib
  summary: 'A library of data processing and reconstruction methods for tomography'
  description: |
    A library of data processing and reconstruction methods for tomography

extra:
  recipe-maintainers:
    - namannimmo10
