{% set name = "httomolib" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ../

build:
  preserve_egg_dir: False
  number: 0

requirements:
  host:
    - python>=3.9
    - pip
    - setuptools
  run:
    - python>=3.9
    - cupy
    - setuptools
    - scipy
    - pillow
    - scikit-image
    - pytest

test:
  requires:
    - pip
    - pytest
  imports:
    - httomolib
    - httomolib.misc
    - httomolib.prep
    - httomolib.recon
  source_files:
    - tests/*
  commands:
    - pip check
    - pytest

about:
  home: https://github.com/DiamondLightSource/httomolib
  summary: 'A library of data processing and reconstruction methods for tomography'
  description: |
    A library of data processing and reconstruction methods for tomography

extra:
  recipe-maintainers:
    - namannimmo10
    - dkazanc
