name: httomolibgpu
channels:
  - conda-forge
  - httomo
dependencies:
  - cupy=12.3.0
  - numpy
  - nvtx
  - scipy
  - python
  - pytest
  - pytest-xdist
  - pytest-cov
  - flake8
  - pyproject-flake8
  - pydocstyle
  - imageio
  - toml
  - ipython
  - h5py
  - astra-toolbox
  - httomo::tomobar
  - scikit-image
