name: httomolib
channels:
  - conda-forge
  - anaconda
  - astra-toolbox
  - savu-dep
dependencies:
  - conda-forge::cupy
  - conda-forge::numpy
  - conda-forge::tomopy
  - conda-forge::scipy
  - conda-forge::python
  - conda-forge::pytest
  - conda-forge::pytest-xdist
  - conda-forge::pytest-cov
  - conda-forge::flake8
  - conda-forge::pyproject-flake8
  - conda-forge::pydocstyle
  - conda-forge::imageio
  - conda-forge::toml
  - anaconda::ipython
  - anaconda::h5py
  - astra-toolbox::astra-toolbox
  - savu-dep::tomobar
  - savu-dep::larix
