name: httomolib
channels:
  - conda-forge
  - anaconda
  - astra-toolbox
  - httomo
dependencies:
  - conda-forge::cupy
  - conda-forge::numpy<=1.23
  - conda-forge::nvtx
  - conda-forge::tomopy
  - conda-forge::scipy
  - conda-forge::python
  - conda-forge::pytest
  - conda-forge::pytest-xdist
  - conda-forge::pytest-cov
  - conda-forge::flake8
  - conda-forge::pyproject-flake8
  - conda-forge::pydocstyle
  - conda-forge::imageio
  - conda-forge::toml
  - anaconda::ipython
  - anaconda::h5py
  - astra-toolbox::astra-toolbox
  - httomo::tomobar
  - httomo::larix
