name: httomolib
channels:
  - conda-forge
  - anaconda
dependencies:
  - conda-forge::cupy
  - conda-forge::numpy
  - conda-forge::tomopy
  - conda-forge::python
  - conda-forge::pytest
  - conda-forge::pytest-xdist
  - conda-forge::imageio
  - anaconda::ipython
  - anaconda::h5py
