name: httomolibgpu
channels:
  - conda-forge
  - anaconda
  - astra-toolbox
  - httomo
  - rapidsai
dependencies:
  - conda-forge::cupy=12.3.0
  - conda-forge::numpy<=1.24
  - conda-forge::nvtx
  - conda-forge::scipy
  - conda-forge::python
  - conda-forge::pytest
  - conda-forge::pytest-xdist
  - conda-forge::pytest-cov
  - conda-forge::flake8
  - conda-forge::pyproject-flake8
  - conda-forge::pydocstyle
  - conda-forge::imageio
  - conda-forge::toml
  - anaconda::ipython
  - anaconda::h5py
  - astra-toolbox::astra-toolbox
  - httomo::tomobar
  - rapidsai::cucim
