{% set pyproject = load_file_data("../../pyproject.toml", from_recipe_dir=True) %}
{% set proj = pyproject.get("project") %}
{% set name = proj.get("name") %}

package:
  name: {{ name|lower }}
  version: {{ GIT_DESCRIBE_TAG|trim("v") }}

source:
  path: ../../

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
    - setuptools
    - setuptools-git-versioning
  run:
    - python
    - numpy>= 1.20, <= 1.25
    - cupy<=12.3.0
    - cucim
    - astra-toolbox
    - nvtx
    - tomobar
    - setuptools
    - scipy
    - pillow
    - scikit-image
    - pytest

test:
  requires:
    - pip
    - pytest
  imports:
    - httomolibgpu
    - httomolibgpu.cupywrapper
    - httomolibgpu.misc
    - httomolibgpu.prep
    - httomolibgpu.recon
  source_files:
    - tests/*
  commands:
    - pip check
    - pytest

about:
  home: https://github.com/DiamondLightSource/httomolibgpu
  summary: 'A library of GPU-accelerated data processing and reconstruction methods for tomography'
  description: |
    A library of GPU-accelerated data processing and reconstruction methods for tomography

extra:
  recipe-maintainers:
    - namannimmo10
    - dkazanc
