{% set name = "httomolibgpu" %}

package:
  name: {{ name|lower }}
  version: {{ environ['VERSION'] }}

source:
  path: ../../

build:
  preserve_egg_dir: False
  number: 0

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - numpy
    - cupy
    - tomopy
    - astra-toolbox
    - nvtx
    - tomobar
    - setuptools
    - scipy
    - pillow
    - scikit-image
    - pytest

test:
  requires:
    - pip
    - pytest
  imports:
    - httomolibgpu
    - httomolibgpu.misc
    - httomolibgpu.prep
    - httomolibgpu.recon
  source_files:
    - tests/*
  commands:
    - pip check
    - pytest

about:
  home: https://github.com/DiamondLightSource/httomolibgpu
  summary: 'A library of GPU-accelerated data processing and reconstruction methods for tomography'
  description: |
    A library of GPU-accelerated data processing and reconstruction methods for tomography

extra:
  recipe-maintainers:
    - namannimmo10
    - dkazanc
