name: httomolibgpu tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  iris-gpu:
    runs-on: iris-gpu
    container:
      image: nvidia/cuda:12.6.3-devel-ubi8
      env:
        NVIDIA_VISIBLE_DEVICES: ${{ env.NVIDIA_VISIBLE_DEVICES }}

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Create conda environment
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: conda/environment.yml
          environment-name: httomo
          post-cleanup: 'all'
          init-shell: bash

      - name: Install httomolibgpu
        run: |
          pip install .[dev]
          micromamba list

      - name: Run tests
        run: |
          pytest tests/
