name: httomolib CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-linux:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2

      # setup Python 3.9
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      # install dependencies with conda
      - name: Install dependencies with Conda
        run: |
          conda env create httomolib --file conda/environment.yml
          conda run -n httomolib python setup.py develop

      # run tests
      - name: Run CPU and GPU tests
        run: |
          conda run -n httomolib pytest -v
