name: httomolibgpu tests on Iris

on:
  - pull_request
  - push

jobs:
  build-linux:
    runs-on: iris-gpu
    container:
      image: nvidia/cuda:11.6.2-devel-ubi8
      env:
        NVIDIA_VISIBLE_DEVICES: ${{ env.NVIDIA_VISIBLE_DEVICES }}

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
        with:
          ref: "main"
          fetch-depth: 0

      - name: Create conda environment
        run: |
          conda activate "${{ env.NVIDIA_VISIBLE_DEVICES }}"
          conda install conda-forge::mamba
          conda list

      - name: Install httomolibgpu
        run: |
          conda run -n httomolibgpu pip install -e .
          conda list

      - name: Run tests
        run: |     
          $CONDA/bin/conda run -n httomolibgpu pytest
