name: httomolibgpu tests on Iris

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    runs-on: iris-gpu
    container:
      image: nvidia/cuda:11.6.2-devel-ubi8
      env:
        NVIDIA_VISIBLE_DEVICES: ${{ env.NVIDIA_VISIBLE_DEVICES }}

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Create conda environment
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: conda/environment.yml
          environment-name: httomo
          post-cleanup: 'all'
          init-shell: bash

      - name: Install httomolibgpu
        run: |
          pip install .[dev]
          micromamba list

      - name: Run tests
        run: |
          pytest tests/

      - name: Build api docs
        run: sphinx-apidoc -feT -t=./docs/source/_templates -o ./docs/source/api ./httomolibgpu

      - name: Build html
        run: sphinx-build -a -E -b html ./docs/source/ ./docs/build/

      - name: Run ghp-import
        run: ghp-import -n -p -f ./docs/build
        env:
          GITHUB_TOKEN: ${{ github.token }}