name: httomolibgpu tests on Iris

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    runs-on: iris-gpu
    container:
      image: mambaorg/micromamba:1.5.8-focal-cuda-11.7.1
      env:
        NVIDIA_VISIBLE_DEVICES: ${{ env.NVIDIA_VISIBLE_DEVICES }}

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
        with:
          ref: "main"
          fetch-depth: 0

      - name: Install dependencies in base conda env
        run: |
          micromamba install -y -n base -f conda/environment.yml

      - name: Install httomolibgpu
        run: |
          pip install .[dev]
          micromamba list

      - name: Run tests
        run: |     
          pytest tests/
